wallets:
  - address: "E4BdAz8TmRZRXRR1JBhpkxYRBnspNeyznttm6U6xPdVJ"
    label: "wm-09"
  - address: "8dAMwTqQJxHmYw1TNNn5J1Fid3QE9EyaymcQ69kkGVJE"
    label: "wm-08"
  - address: "AP1S7WapVZ5DwEi3wc2o2RG6Rq1C4Auj6YvQDS5T9eGe"
    label: "wm-07"
  - address: "ADW8H9197SAYLy9aKs2CxCiz6662QMidDhRLUwQraWTC"
    label: "wm-06"
  - address: "AuLT4gVtcdnQnswjypHEuW4FXdBKTfUs5DyhMFQnDZPQ"
    label: "wm-05"
  - address: "8quVxKzc21GybehhMKwhiuuVks9eg1carGoBUuqpZJ1a"
    label: "wm-04"
  - address: "EQ36RJowwSGz1DBXMRBydR7hiMjswj2ZdgfpyhdaxJcF"
    label: "wm-03"
  - address: "EoN2ef1hPAT9WCw6gjkgp6922WvagdCcjkJGkXqB33aW"
    label: "wm-02"
  - address: "G3K9kWBDUmtnxypFZSzZDdMS9d8GWnZUrbsvobSJkwVG"
    label: "wm-01"
  - address: "MfDuWeqSHEqTFVYZ7LoexgAK9dxk7cy4DFJWjWMGVWa"
    label: "wm"

